version: "3.8"

services:
    postgres:
        image: postgres:15
        container_name: polaris-postgres
        restart: always
        environment:
            POSTGRES_USER: polaris_user
            POSTGRES_PASSWORD: polaris_password
            POSTGRES_DB: polaris
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./polaris-backend/data/init.sql:/docker-entrypoint-initdb.d/init.sql

    backend:
        build: ./polaris-backend
        container_name: polaris-backend
        restart: always
        depends_on:
            - postgres
        environment:
            PORT: "8080"
            DATABASE_URL: "postgresql://polaris_user:polaris_password@postgres:5432/polaris"
        ports:
            - "8080:8080"

    frontend:
        build: ./polaris-dashboard
        container_name: polaris-dashboard
        restart: always
        depends_on:
            - backend
        ports:
            - "3000:3000"

volumes:
    postgres_data:
